#!/usr/bin/env python3
"""Generate load_rel_symbols.gdb from config.json and PLF ELF headers."""

import json
import os
import struct
import sys


# REL section index -> ELF section name
REL_SECTIONS = {
    1: ".text",
    4: ".rodata",
    5: ".data",
    6: ".bss",
}


def get_elf_sections(plf_path):
    """Parse ELF section headers and return set of section names."""
    sections = set()
    try:
        with open(plf_path, "rb") as f:
            magic = f.read(4)
            if magic != b"\x7fELF":
                return sections
            f.seek(0)
            ehdr = f.read(52)  # ELF32 header
            e_shoff = struct.unpack(">I", ehdr[32:36])[0]
            e_shentsize = struct.unpack(">H", ehdr[46:48])[0]
            e_shnum = struct.unpack(">H", ehdr[48:50])[0]
            e_shstrndx = struct.unpack(">H", ehdr[50:52])[0]

            # Read section header string table
            f.seek(e_shoff + e_shstrndx * e_shentsize)
            shstrtab_hdr = f.read(e_shentsize)
            strtab_off = struct.unpack(">I", shstrtab_hdr[16:20])[0]
            strtab_size = struct.unpack(">I", shstrtab_hdr[20:24])[0]
            f.seek(strtab_off)
            strtab = f.read(strtab_size)

            # Read each section header
            for i in range(e_shnum):
                f.seek(e_shoff + i * e_shentsize)
                shdr = f.read(e_shentsize)
                sh_name_idx = struct.unpack(">I", shdr[0:4])[0]
                # Extract null-terminated string
                end = strtab.index(b"\x00", sh_name_idx)
                name = strtab[sh_name_idx:end].decode("ascii", errors="replace")
                if name:
                    sections.add(name)
    except Exception:
        pass
    return sections


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)

    if len(sys.argv) > 1:
        build_dir = os.path.abspath(sys.argv[1])
    else:
        build_dir = os.path.join(repo_root, "build", "GZ2E01")

    config_path = os.path.join(build_dir, "config.json")
    if not os.path.exists(config_path):
        print("Error: config.json not found at %s" % config_path)
        sys.exit(1)

    with open(config_path) as f:
        cfg = json.load(f)

    # Build module_id -> (plf_path, set of section names)
    modules = {}
    for m in cfg.get("modules", []):
        mid = m.get("module_id")
        name = m.get("name")
        if mid is not None and name:
            plf = os.path.join(build_dir, name, "%s.plf" % name)
            if os.path.exists(plf):
                elf_sections = get_elf_sections(plf)
                modules[mid] = (plf, elf_sections)

    out_path = os.path.join(build_dir, "load_rel_symbols.gdb")

    with open(out_path, "w") as f:
        f.write("# Auto-generated by gen_gdb_rel_loader.py — do not edit\n")
        f.write("# Source this file, then run: load-all-symbols\n\n")

        # load-dol-symbols
        elf_path = os.path.join(build_dir, "framework.elf")
        f.write("define load-dol-symbols\n")
        f.write("  symbol-file %s\n" % elf_path)
        f.write("  printf \"Loaded DOL symbols\\n\"\n")
        f.write("end\n\n")

        # Per-module loader commands
        for mid in sorted(modules.keys()):
            plf, elf_sections = modules[mid]

            # Determine which extra sections this PLF actually has
            extra_secs = []
            for sec_idx, sec_name in sorted(REL_SECTIONS.items()):
                if sec_idx == 1:
                    continue  # .text is the primary argument
                if sec_name in elf_sections:
                    extra_secs.append((sec_idx, sec_name))

            f.write("define __rel_%d\n" % mid)
            # Read .text (section index 1)
            f.write("  set $__t = *(unsigned int*)($__si + 8) & ~1\n")
            f.write("  set $__ts = *(unsigned int*)($__si + 12)\n")

            # Read only sections that exist in this PLF
            for sec_idx, sec_name in extra_secs:
                var = sec_name.replace(".", "_")
                f.write("  set $%s = 0\n" % var)
                f.write("  if $__ns > %d\n" % sec_idx)
                f.write("    set $%s = *(unsigned int*)($__si + %d) & ~1\n" % (var, sec_idx * 8))
                f.write("  end\n")

            f.write("  if $__t != 0 && $__ts != 0\n")

            # Build add-symbol-file with only existing sections
            cmd = "add-symbol-file %s $__t" % plf
            for sec_idx, sec_name in extra_secs:
                var = sec_name.replace(".", "_")
                cmd += " -s %s $%s" % (sec_name, var)
            f.write("    %s\n" % cmd)
            f.write("    set $__loaded = $__loaded + 1\n")

            f.write("  end\n")
            f.write("end\n\n")

        # load-rel-symbols: walk the OS module linked list
        f.write("define load-rel-symbols\n")
        f.write("  set confirm off\n")
        f.write("  set $__mod = *(unsigned int*)0x800030C8\n")
        f.write("  set $__loaded = 0\n")
        f.write("  while $__mod != 0\n")
        f.write("    set $__id = *(unsigned int*)($__mod)\n")
        f.write("    set $__next = *(unsigned int*)($__mod + 4)\n")
        f.write("    set $__ns = *(unsigned int*)($__mod + 0x0C)\n")
        f.write("    set $__si = *(unsigned int*)($__mod + 0x10)\n")

        for mid in sorted(modules.keys()):
            f.write("    if $__id == %d\n" % mid)
            f.write("      __rel_%d\n" % mid)
            f.write("    end\n")

        f.write("    set $__mod = $__next\n")
        f.write("  end\n")
        f.write("  set confirm on\n")
        f.write('  printf "Loaded %d REL modules\\n", $__loaded\n')
        f.write("end\n\n")

        # load-all-symbols
        f.write("define load-all-symbols\n")
        f.write("  load-dol-symbols\n")
        f.write("  load-rel-symbols\n")
        f.write("end\n")

    print("Generated %s (%d module mappings)" % (out_path, len(modules)))


if __name__ == "__main__":
    main()
